In [1]:
import pandas as pd

SERIES FROM LISTS

In [2]:
country = ["India","Pakistan" , "USA", "Srilanka"]
pd.Series(country)

0       India
1    Pakistan
2         USA
3    Srilanka
dtype: object

In [3]:
# INTEGER
runs = [12, 18, 45, 264, 100]
pd.Series(runs)

0     12
1     18
2     45
3    264
4    100
dtype: int64

In [5]:
# custom index
marks = [67, 57 , 89, 100]
subjects = ['maths' , 'english','science' ,'hindi']

pd.Series(marks , index = subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [6]:
# Setting a name
marks = pd.Series(marks, index = subjects , name = 'Krishna ke marks')
marks

maths       67
english     57
science     89
hindi      100
Name: Krishna ke marks, dtype: int64

SERIES FROM DICT

In [8]:
marks = {
    "maths": 67,
    "english": 57,
    "science": 89,
    "hindi":100
    
}
marks_series  = pd.Series(marks , name = "Krishna ke marks ")
marks_series

maths       67
english     57
science     89
hindi      100
Name: Krishna ke marks , dtype: int64

SERIES ATTRIBUTES

In [22]:
# size of series bta dega ki kitne element hai
a = marks_series.size
print(a)

# dtype  data type bta dega
b = marks_series.dtype
print(b)

# name  [topic ke baare mein bta  dega if mention hai toh]
c = marks_series.name
print(c)

# is_unique
d = marks_series.is_unique
print (d)

pd.Series([1, 1, 2, 2, 2, 3, 4, 5 ,56]).is_unique # FALSE DEGA BECAUSE REPEATED NUMBER HAI 


# index 

e = marks_series.index
print(a)
# values

f = marks_series.values
print(f)

# keys() 
k = marks_series.keys()
print(k)

4
int64
Krishna ke marks
True
4
[ 67  57  89 100]
Index(['maths', 'english', 'science', 'hindi'], dtype='object')

SERIES USING read_csv

In [23]:
# with one col

subs = pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [24]:
"""squeeze() dataframe ko series mein convert kar dega """
vk  = pd.read_csv('kohli_ipl.csv', index_col = "match_no" ).squeeze()  
vk.reset_index()

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [25]:
movie = pd.read_csv('bollywood.csv', index_col = 'movie').squeeze()
movie

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [27]:
# head ( preview dega) and tail
subs.head()
vk.tail()

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [29]:
# sample ( randomly koi bhi movie nikal ke dikha dega)
movie.sample(5)

movie
Golmaal Again                                      Ajay Devgn
Netaji Subhas Chandra Bose: The Forgotten Hero    Vinay Anand
Bumboo                                             Kavin Dave
Chashme Baddoor (2013 film)                         Ali Zafar
Chori Chori (2003 film)                            Ajay Devgn
Name: lead, dtype: object

In [31]:
# value_count (every unique value kitni baar aayi hai ) -> movies
movie.value_counts(normalize = True)
"normalize  = True means (frequencty of that value / total non null values)"  # kitne percentage hai total mein se

"""value count null value ko drop kar deta hai"""
movie.value_counts(dropna = False)  # null value ko drop nhi karega

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Diganth              1
Parveen Kaur         1
Seema Azmi           1
Akanksha Puri        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [37]:
# sort_values 
vk.sort_values(ascending = False)  # this is temporary
vk = vk.copy()

vk_copy = vk.sort_values(inplace  = True) # this is parmanent change
vk_copy
# """inplace = True """ # permanent change dega

In [79]:
# sort_index
movie.sort_index(ascending = False)

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...
2 States (2014 film)              Arjun Kapoor
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object

In [80]:
vk.sort_index(ascending  = False)

match_no
215     7
214    25
213    73
212    20
211     0
       ..
5       1
4      12
3      13
2      23
1       1
Name: runs, Length: 215, dtype: int64

SERIES MATHS METHODS

In [54]:
# count  (only non missing values)
vk.count()

# sum
subs.sum()

# product
vk.product()

# mean , median , mode ,std , var

subs.mean()
vk.median()
subs.std()
vk.var()
movie.mode()  # more frequent

           lead
0  Akshay Kumar

In [38]:
# min /max
subs.min()
subs.max()
vk.max()
vk.min()

0

 DESCRIBE (SUMMARY DEGA)

In [39]:
subs.describe()

       Subscribers gained
count          365.000000
mean           135.643836
std             62.675023
min             33.000000
25%             88.000000
50%            123.000000
75%            177.000000
max            396.000000

SERIES INDEXING

In [43]:
x = [1, 18, 17, 14, 45, 7]  
x[-2]
x[1]

18

In [44]:
movie
movie[-1]

C:\Users\mrkri\AppData\Local\Temp\ipykernel_10732\1539061958.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movie[-1]

'Akshay Kumar'

In [45]:
# slicing
vk[-10:]

movie[-5:]

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

FANCY INDEXING

In [46]:
vk[[1, 3, 4, 5 ,9]]

match_no
1     1
3    13
4    12
5     1
9    21
Name: runs, dtype: int64

In [47]:
# indexing with label
movie['Awara Paagal Deewana']

'Akshay Kumar'

EDITING SERIES

In [49]:
# using indexing
marks_series[1] = 100
marks_series

C:\Users\mrkri\AppData\Local\Temp\ipykernel_10732\3621369324.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks_series[1] = 100

maths       67
english    100
science     89
hindi      100
Name: Krishna ke marks , dtype: int64

In [51]:
# if index is not present then new item add kar dega
marks_series['sst'] = 90
marks_series

maths       67
english    100
science     89
hindi      100
sst         90
Name: Krishna ke marks , dtype: int64

SERIES WITH PYTHON FUNCTIONALLITY